[env:sd2-small-tv-selftest]
platform = espressif8266
board = esp12e
framework = arduino

upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 460800

board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m2m.ld
board_build.filesystem = littlefs

lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  adafruit/Adafruit NeoPixel@^1.15.1

build_flags =
  -D USER_SETUP_LOADED
  -D ST7789_2_DRIVER
  -D TFT_RGB_ORDER=TFT_RGB
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_CS=15
  -D TFT_DC=0
  -D TFT_RST=2
  -D TFT_BL=5
  -D TFT_BACKLIGHT_ON=LOW
  -D LOAD_GLCD
  -D SPI_FREQUENCY=27000000
